web_interface/app/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path
from web_interface.app import views

urlpatterns = [
    # Homepage
    path('', views.index, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('about_me/', views.about_me, name='about_me'),

]

web_interface/core/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""
from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("web_interface.authentication.urls")),
    path("", include("web_interface.app.urls")),
    path("patients_manager/", include("web_interface.patients_manager.urls")),
    path("questions_manager/", include("web_interface.questions_manager.urls"))
]

web_interface/patients_manager/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('index/', views.index, name='patients_index'),
    path('assign/', views.assign, name='assign'),
    path('unassign/<int:patient_id>/', views.unassign, name='unassign'),
    path('assign_questions/<int:patient_id>/', views.assign_questions, name='assign_questions'),
    path('assign_questions/<int:question_id>/<int:patient_id>/', views.assign_question_to_patient,
         name='assign_question_to_patient'),
    path('unassign_questions/<int:question_id>/<int:patient_id>/', views.unassign_question_to_patient,
         name='unassign_question_to_patient'),
    path('view_data/<int:patient_id>/', views.view_data, name='view_data'),
    path('export/', views.export, name='export'),

]

howru_models/models.py
from base64 import b64encode

import pytz
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
# noinspection PyUnresolvedReferences
from django_better_admin_arrayfield.models.fields import ArrayField
from timezonefinder import TimezoneFinder

from howru_helpers import UTCTime

tf = TimezoneFinder()


class Response(models.Model):
    text = models.CharField(max_length=100)
    order = models.IntegerField(null=False)
    question = models.ForeignKey('Question', on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Question(models.Model):
    text = models.CharField(max_length=100)
    creator = models.ForeignKey('Doctor', on_delete=models.CASCADE)
    public = models.BooleanField()
    language = models.CharField(choices=[("GB", "English"), ("ES", "Spanish")], max_length=2)
    assigned_to_all = models.BooleanField()
    frequency = models.CharField(
        choices=[("D", "Daily"), ("W", "Weekly"), ("M", "Monthly"), ("O", "Once")],
        max_length=1, default="D")
    priority = models.IntegerField(default=1)

    def __str__(self):
        return self.text


class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    assigned_questions = models.ManyToManyField(Question, blank=True)
    is_analyst = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Doctor.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.doctor.save()


class Patient(models.Model):
    identifier = models.CharField(primary_key=True, max_length=10)
    name = models.CharField(max_length=100, null=True)
    _picture = models.BinaryField(blank=True, db_column="picture")
    _gender = models.CharField(choices=[("M", "Male"), ("F", "Female"), ("O", "Other")], max_length=1,
                               db_column="gender", null=True)
    timezone = models.CharField(max_length=50, default="Europe/Madrid")
    language = models.CharField(choices=[("GB", "English"), ("ES", "Spanish")], max_length=2)
    username = models.CharField(max_length=20, null=True)
    _schedule = models.DateTimeField(
        db_column="schedule"
    )
    assigned_doctors = models.ManyToManyField(Doctor, blank=True)

    GENDER_MAPPING = {
        "M": {"ES": "Masculino", "GB": "Male"},
        "F": {"ES": "Femenino", "GB": "Female"},
        "O": {"ES": "Otro", "GB": "Other"},
    }

    @classmethod
    def get_timezone_from_location(cls, location):
        latitude, longitude = location['latitude'], location['longitude']
        return tf.timezone_at(lng=longitude, lat=latitude)

    def __str__(self):
        return self.username

    @property
    def picture(self):
        return b64encode(self._picture).decode('utf-8')

    @picture.setter
    def picture(self, value):
        self._picture = open(value, 'rb').read()

    @property
    def schedule(self):
        schedule = self._schedule
        if schedule.tzinfo == pytz.utc:
            schedule = UTCTime.to_locale(time=schedule, timezone=self.timezone)
        return schedule

    @schedule.setter
    def schedule(self, value):
        self._schedule = UTCTime.str_to_localized_datetime(value, timezone=self.timezone)

    @property
    def gender(self):
        return self.GENDER_MAPPING[self._gender][self.language]

    @gender.setter
    def gender(self, value):
        if value in ["Masculino", "Male"]:
            gender = "M"
        elif value in ["Femenino", "Female"]:
            gender = "F"
        else:
            gender = "O"
        self._gender = gender


class JournalEntry(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)

    class Meta:
        abstract = True

    def __str__(self):
        return "{} - {} - {}".format(self.question, self.patient, self.doctor)


class PendingQuestion(JournalEntry):
    answering = models.BooleanField()


class AnsweredQuestion(JournalEntry):
    answer_date = models.DateTimeField()
    response = models.ForeignKey(Response, on_delete=models.CASCADE)

    def __str__(self):
        base = str(super())
        return f'{base} - {self.response} - {self.answer_date}'

web_interface/patients_manager/forms.py
from datetime import datetime

import pytz
from django import forms
from django.core.exceptions import ValidationError

from howru_helpers import UTCTime
from howru_models.models import Patient


class AssignPatientForm(forms.Form):
    username = forms.CharField()

    def clean(self):
        self.cleaned_data['username'] = self.cleaned_data['username'].replace('@', '')


class ExportForm(forms.Form):
    patients = forms.ModelMultipleChoiceField(queryset=None)
    start_date = forms.DateTimeField()
    end_date = forms.DateTimeField()

    def __init__(self, doctor, *args, **kwargs):
        super(ExportForm, self).__init__(*args, **kwargs)
        self.fields['patients'].queryset = doctor.patient_set.all()

    def clean(self):
        start_date = self.cleaned_data['start_date']
        end_date = self.cleaned_data['end_date']
        # Add time to dates
        self.cleaned_data['start_date'] = datetime(day=start_date.day, month=start_date.month, year=start_date.year,
                                                   hour=0, minute=0, second=0, tzinfo=pytz.UTC)
        self.cleaned_data['end_date'] = datetime(day=end_date.day, month=end_date.month, year=end_date.year, hour=0,
                                                 minute=0,second=0, tzinfo=pytz.UTC)
        if self.cleaned_data['start_date'] > self.cleaned_data['end_date']:
            raise ValidationError("Start date must be before end date")

web_interface/patients_manager/views.py
import csv
import os

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count, CharField, Value
from django.db.models.functions import Cast, ExtractDay, ExtractMonth, ExtractYear, Concat
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from howru_models.models import Patient, PendingQuestion
from web_interface.patients_manager.forms import AssignPatientForm, ExportForm


# Create your views here.


@login_required
def index(request):
    """
    Shows all assigned patients from the request's doctor. Allows pagination.
    Available options:
        - View data
        - Assign questions
        - Delete patient
    """
    doctor = request.user.doctor
    if 'search' in request.GET:
        term = request.GET['search']
        all_patients = doctor.patient_set.filter(name__icontains=term).order_by('username')
    else:
        all_patients = doctor.patient_set.all().order_by('username')
    page = request.GET.get('page', 1)
    paginator = Paginator(all_patients, settings.PAGE_SIZE)
    try:
        patients = paginator.page(page)
    except PageNotAnInteger:
        patients = paginator.page(1)
    except EmptyPage:
        patients = paginator.page(paginator.num_pages)
    request.session['patients_page'] = page
    context = {
        'patients': patients,
        'success_msg': request.session.pop('message', None)
    }
    return render(request, 'patients_manager/index.html', context)


@login_required
def assign(request):
    """
    Assigns a patient to the request's doctor.
    Required param: username.
    Data clean: remove @ and case insensitive.
    """
    not_found = False
    if request.method == "POST":
        form = AssignPatientForm(request.POST)
        if form.is_valid():
            try:
                username = form.cleaned_data.get('username')
                patient = Patient.objects.get(username__iexact=username)
                if patient in request.user.doctor.patient_set.all():
                    request.session['message'] = f'Patient {username} is already in your patients'
                else:
                    request.user.doctor.patient_set.add(patient)
                    # Assign assigned_to_all questions
                    questions = request.user.doctor.assigned_questions.filter(assigned_to_all=True)
                    for question in questions:
                        pending = PendingQuestion(doctor=request.user.doctor,
                                                  question=question,
                                                  patient=patient,
                                                  answering=False)
                        pending.save()
                    request.session['message'] = f'Patient {username} has been successfully added'
                page = request.session.pop('patients_page', 1)
                return redirect(f'{reverse("patients_index")}?page={page}')
            except Patient.DoesNotExist:
                not_found = True
    else:
        form = AssignPatientForm()
    return render(request, 'patients_manager/assign.html', context={"form": form, "not_found": not_found})


@login_required
def unassign(request, patient_id):
    """
    Removes a patient from request's doctor assigned patients
    :param patient_id (int)
    """
    patient = Patient.objects.get(identifier=patient_id)
    context = {"patient": patient}
    if request.method == "POST":
        request.user.doctor.patient_set.remove(patient)
        # Delete pending questions
        pending = PendingQuestion.objects.filter(patient=patient, doctor=request.user.doctor).delete()
        request.session['message'] = f'Patient {patient} has been successfully deleted'
        page = request.session.pop('patients_page', 1)
        # FIXME
        return redirect(f'{reverse("patients_index")}?page={page}')
    return render(request, 'patients_manager/unassign.html', context)


@login_required
def assign_questions(request, patient_id):
    """
    Shows request's doctor questions that can be assigned to the patient.
    Avaliable options:
        - Assign/Unassign questions
    :param patient_id (int):
    """
    all_questions = request.user.doctor.assigned_questions.all().order_by('text')
    page = request.GET.get('page', 1)
    paginator = Paginator(all_questions, settings.PAGE_SIZE)
    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        questions = paginator.page(1)
    except EmptyPage:
        questions = paginator.page(paginator.num_pages)
    request.session['patient_questions_page'] = page
    context = {
        'patient': Patient.objects.get(identifier=patient_id),
        'questions': questions,
        'success_msg': request.session.pop('message', None)
    }
    return render(request, 'patients_manager/assign_questions.html', context)


@login_required
def assign_question_to_patient(request, question_id, patient_id):
    """
    Assigns a question to a patient bu creating a PendingQuestion
    :param question_id (int)
    :param patient_id (int)
    """
    pending_question = PendingQuestion(doctor=request.user.doctor,
                                       question_id=question_id,
                                       patient_id=patient_id,
                                       answering=False)
    pending_question.save()
    # request.session['message'] = "Question successfully assigned to patient"
    page = request.session.pop('patient_questions_page', 1)
    return redirect(f'{reverse("assign_questions")}/{patient_id}?page={page}')


@login_required
def unassign_question_to_patient(request, question_id, patient_id):
    """
    Unassigns a question to a patient by removing the corresponding PendingQuestion
    :param question_id (int)
    :param patient_id (int)
    """
    pending_question = PendingQuestion.objects.get(doctor=request.user.doctor, question_id=question_id,
                                                   patient_id=patient_id)
    pending_question.delete()
    # request.session['message'] = "Question successfully unassigned to patient"
    page = request.session.pop('patient_questions_page', 1)
    return redirect(f'{reverse("assign_questions")}/{patient_id}?page={page}')


@login_required
def view_data(request, patient_id):
    """
    Shows answered questions data from a patient.
    :param patient_id (int):
    """
    answered_set = Patient.objects.get(identifier=patient_id).answeredquestion_set
    if 'search' in request.GET:
        term = request.GET['search']
        all_questions = answered_set.filter(question__text__icontains=term, doctor=request.user.doctor).values(
            'question', 'question__text').annotate(n=Count('response')).order_by('question')
    else:
        all_questions = answered_set.filter(doctor=request.user.doctor).values('question', 'question__text').annotate(
            n=Count('response')).order_by('question')

    page = request.GET.get('page', 1)
    paginator = Paginator(all_questions, settings.PAGE_SIZE)
    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        questions = paginator.page(1)
    except EmptyPage:
        questions = paginator.page(paginator.num_pages)
    list_of_questions = dict()
    for question in questions:
        pie_data = list(
            all_questions.filter(question_id=question['question']).values('response__text',
                                                                          'response__order').annotate(
                n=Count('response')))
        line_data = list(all_questions.filter(question_id=question['question']).values('response', 'question').order_by(
            'answer_date').annotate(
            day=Cast(ExtractDay('answer_date'), CharField()),
            month=Cast(ExtractMonth('answer_date'), CharField()),
            year=Cast(ExtractYear('answer_date'), CharField()),
            date=Concat('day', Value('/'), 'month', Value('/'), 'year', output_field=CharField())).values(
            'response__text',
            'response__order',
            'date'))
        list_of_questions[question['question']] = {
            'pie_data': pie_data,
            'line_data': line_data
        }
    context = {
        'questions': questions,
        'list_of_questions': list_of_questions,
        'patient': Patient.objects.get(identifier=patient_id)
    }
    return render(request, 'patients_manager/view_data.html', context)


def create_csv(patients, file_path, start_date, end_date):
    """
    Creates a CSV file with patients data
    :param patients (list)
    :param file_path (str)
    :param start_date (datetime)
    :param end_date (datetime)
    """
    with open(file_path, 'w') as csv_file:
        writer = csv.writer(csv_file)
        writer.writerow(["Patient username", "Question", "Answer", "Date"])
        for patient in patients:
            for answered_question in patient.answeredquestion_set.filter(answer_date__lte=end_date,
                                                                         answer_date__gte=start_date):
                writer.writerow([
                    patient,
                    answered_question.question,
                    answered_question.response,
                    answered_question.answer_date.strftime('%Y-%m-%d %H:%M:%S')
                ])


def patients_to_csv(patients, doctor, start_date, end_date):
    """
    Creates a CSV file with patients data and sends it to the user.
    :param patients (list)
    :param doctor (doctor)
    :param start_date (datetime)
    :param end_date (datetime)
    """
    filename = f'patients_{doctor}.csv'
    file_path = os.path.join(settings.CSV_DIR, filename)
    create_csv(patients, file_path, start_date, end_date)
    with open(file_path, 'rb') as file:

web_interface/patients_manager/templates/patients_manager/assign.html
{% extends "layouts/base.html" %}
{% block title %} Patients Manager {% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-5" style="margin: 0 auto;float: none;margin-bottom: 10px;">
        <div class="card">
            {% if not_found %}
            <div class="alert alert-danger">
                <strong>Patient username not found</strong>
            </div>
            {% endif %}
            <div class="card-body">
                <div class="col-md-12">
                    <form action="{% url 'assign' %}" class="form-horizontal"
                          enctype="multipart/form-data"
                          method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input autocomplete="username" class="form-control" id="username" name="username"
                                   placeholder="Username" required type="text">
                            <span class="input-group-append">
                            <button class="btn btn-primary" type="submit">
                              <svg class="c-icon">
                                <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-smile-plus"></use>
                              </svg> Add
                            </button>
                            </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascripts %}
<!-- Specific Page JS goes HERE  -->
{% endblock javascripts %}

web_interface/patients_manager/templates/patients_manager/assign_questions.html
{% extends "layouts/base.html" %}
{% load is_question_assigned from templatetags %}
{% load paginate from pagination %}
{% block title %} Patients Manager {% endblock %}

{% block content %}
<style>
    html, body {
    max-width: 100%;
    overflow-x: hidden;
}
</style>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            {% if success_msg %}
            <div class="alert alert-success">
                <strong>{{ success_msg }}</strong>
            </div>
            {% endif %}
            <div class="card-header"><strong>Assign questions to patient {{ patient }}</strong></div>
            <div class="card-body">
                {% if questions %}
                <table class="table table-responsive-sm table-bordered table-striped table-sm">
                    <thead>
                    <tr>
                        <th style="text-align: center; vertical-align: middle;">Question text</th>
                        <th style="text-align: center; vertical-align: middle;">Possible responses</th>
                        <th style="text-align: center; vertical-align: middle;">Frequency</th>
                        <th style="text-align: center; vertical-align: middle;">Priority</th>
                        <th style="text-align: center; vertical-align: middle;">Privacy</th>
                        <th style="text-align: center; vertical-align: middle;">Creator</th>
                        <th style="text-align: center; vertical-align: middle;">Language</th>
                        <th style="text-align: center; vertical-align: middle;">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for question in questions %}
                    <tr>
                        <td style="text-align: center; vertical-align: middle;">
                            {{ question.text }}
                        </td>
                        <td style="text-align: center; vertical-align: middle;">
                            {% for response in question.response_set.all %}
                            {{ response }} <br>
                            {% endfor %}
                        </td>
                        <td style="text-align: center; vertical-align: middle;">
                            {{ question.get_frequency_display }}
                        </td>
                        <td style="text-align: center; vertical-align: middle;">
                            {{ question.priority }}
                        </td>
                        <td style="text-align: center; vertical-align: middle;">
                            {% if question.public %}
                            <span class="badge badge-success">Public</span>
                            {% else %}
                            <span class="badge badge-danger">Private</span>
                            {% endif %}
                        </td>
                        <td style="text-align: center; vertical-align: middle;">
                            {{ question.creator.user.username }}
                            {% if question.creator.user.username == request.user.username %}
                            (You)
                            {% endif %}
                        </td>
                        <td style="text-align: center; vertical-align: middle;">
                            {{ question.get_language_display }}
                        </td>
                        <td style="text-align: center; vertical-align: middle;">
                            {% if not patient|is_question_assigned:question %}
                            <a href="{% url 'assign_question_to_patient' question.id patient.identifier %}">
                                <button class="btn btn-pill btn-primary" type="button">
                                    <svg class="c-icon">
                                        <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-task"></use>
                                    </svg>&nbsp;
                                    Assign
                                </button>
                            </a>
                            {% else %}
                            <a href="{% url 'unassign_question_to_patient' question.id patient.identifier %}">
                                <button class="btn btn-pill btn-danger" type="button">
                                    <svg class="c-icon">
                                        <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-x-circle"></use>
                                    </svg>&nbsp;
                                    Unassign
                                </button>
                            </a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% if questions.has_other_pages %}
                <ul class="pagination" style="justify-content: center;">
                    {% if questions.number == 1 %}
                    <li class="page-item"><a class="page-link disabled">⇤</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link"
                                             href="?page=1">⇤</a></li>
                    {% endif %}
                    {% if questions.has_previous %}
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ questions.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link disabled">&laquo;</a></li>
                    {% endif %}
                    {% for i in questions.paginator|paginate:questions.number %}
                    {% if questions.number == i %}
                    <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                    {% endfor %}
                    {% if questions.has_next %}
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ questions.next_page_number }}">&raquo;</a>
                    </li>
                    {% else %}
                    <li class="page-item"><a class="page-link disabled">&raquo;</a></li>
                    {% endif %}
                    {% if questions.number == questions.paginator.num_pages %}
                    <li class="page-item"><a class="page-link disabled">⇥</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ questions.paginator.num_pages }}">⇥</a></li>
                    {% endif %}
                </ul>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascripts %}
<!-- Specific Page JS goes HERE  -->
{% endblock javascripts %}

web_interface/patients_manager/templates/patients_manager/export.html
{% extends "layouts/base.html" %}
{% load get_latest_answer_time from templatetags %}
{% load paginate from pagination %}
{% load get_url from get_search_url %}
{% block title %} Patients Manager {% endblock %}

{% block content %}
<style>
html, body {
    max-width: 100%;
    overflow-x: hidden;
}

</style>

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div>
                    <div class="col-sm-12 input">
                        {% if form.errors %}
                        {% for field in form %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                        {% endif %}
                        <form enctype='multipart/form-data' method="post">
                            {% csrf_token %}
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label" for="patients">Select patients to
                                    export</label>
                                <div class="col-md-9">
                                    <select class="form-control" id="patients" multiple=""
                                            name="patients"
                                            required size="10">
                                        {% for patient in form.fields.patients.choices %}
                                        <option value="{{patient.0}}">{{patient.1}}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label" for="start_date">Start date</label>
                                <div class="col-md-9">
                                    <input class="form-control" id="start_date" name="start_date" placeholder="date"
                                           required type="date">
                                    <span
                                            class="help-block">Please enter a valid date
                                    </span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label" for="end_date">End date</label>
                                <div class="col-md-9">
                                    <input class="form-control" id="end_date" name="end_date" placeholder="date"
                                           required type="date">
                                    <span
                                            class="help-block">Please enter a valid date
                                    </span>
                                </div>
                            </div>
                            <div class="text-center">
                                <button class="btn btn-sm btn-primary" name="login" type="submit">Submit</button>
                                <button class="btn btn-sm btn-danger" type="reset"> Reset</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascripts %}
<!-- Specific Page JS goes HERE  -->
{% endblock javascripts %}