web_interface/app/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path
from web_interface.app import views

urlpatterns = [
    # Homepage
    path('', views.index, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('about_me/', views.about_me, name='about_me'),

]

web_interface/core/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""
from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("web_interface.authentication.urls")),
    path("", include("web_interface.app.urls")),
    path("patients_manager/", include("web_interface.patients_manager.urls")),
    path("questions_manager/", include("web_interface.questions_manager.urls"))
]

howru_models/models.py
from base64 import b64encode

import pytz
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
# noinspection PyUnresolvedReferences
from django_better_admin_arrayfield.models.fields import ArrayField
from timezonefinder import TimezoneFinder

from howru_helpers import UTCTime

tf = TimezoneFinder()


class Response(models.Model):
    text = models.CharField(max_length=100)
    order = models.IntegerField(null=False)
    question = models.ForeignKey('Question', on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Question(models.Model):
    text = models.CharField(max_length=100)
    creator = models.ForeignKey('Doctor', on_delete=models.CASCADE)
    public = models.BooleanField()
    language = models.CharField(choices=[("GB", "English"), ("ES", "Spanish")], max_length=2)
    assigned_to_all = models.BooleanField()
    frequency = models.CharField(
        choices=[("D", "Daily"), ("W", "Weekly"), ("M", "Monthly"), ("O", "Once")],
        max_length=1, default="D")
    priority = models.IntegerField(default=1)

    def __str__(self):
        return self.text


class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    assigned_questions = models.ManyToManyField(Question, blank=True)
    is_analyst = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Doctor.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.doctor.save()


class Patient(models.Model):
    identifier = models.CharField(primary_key=True, max_length=10)
    name = models.CharField(max_length=100, null=True)
    _picture = models.BinaryField(blank=True, db_column="picture")
    _gender = models.CharField(choices=[("M", "Male"), ("F", "Female"), ("O", "Other")], max_length=1,
                               db_column="gender", null=True)
    timezone = models.CharField(max_length=50, default="Europe/Madrid")
    language = models.CharField(choices=[("GB", "English"), ("ES", "Spanish")], max_length=2)
    username = models.CharField(max_length=20, null=True)
    _schedule = models.DateTimeField(
        db_column="schedule"
    )
    assigned_doctors = models.ManyToManyField(Doctor, blank=True)

    GENDER_MAPPING = {
        "M": {"ES": "Masculino", "GB": "Male"},
        "F": {"ES": "Femenino", "GB": "Female"},
        "O": {"ES": "Otro", "GB": "Other"},
    }

    @classmethod
    def get_timezone_from_location(cls, location):
        latitude, longitude = location['latitude'], location['longitude']
        return tf.timezone_at(lng=longitude, lat=latitude)

    def __str__(self):
        return self.username

    @property
    def picture(self):
        return b64encode(self._picture).decode('utf-8')

    @picture.setter
    def picture(self, value):
        self._picture = open(value, 'rb').read()

    @property
    def schedule(self):
        schedule = self._schedule
        if schedule.tzinfo == pytz.utc:
            schedule = UTCTime.to_locale(time=schedule, timezone=self.timezone)
        return schedule

    @schedule.setter
    def schedule(self, value):
        self._schedule = UTCTime.str_to_localized_datetime(value, timezone=self.timezone)

    @property
    def gender(self):
        return self.GENDER_MAPPING[self._gender][self.language]

    @gender.setter
    def gender(self, value):
        if value in ["Masculino", "Male"]:
            gender = "M"
        elif value in ["Femenino", "Female"]:
            gender = "F"
        else:
            gender = "O"
        self._gender = gender


class JournalEntry(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)

    class Meta:
        abstract = True

    def __str__(self):
        return "{} - {} - {}".format(self.question, self.patient, self.doctor)


class PendingQuestion(JournalEntry):
    answering = models.BooleanField()


class AnsweredQuestion(JournalEntry):
    answer_date = models.DateTimeField()
    response = models.ForeignKey(Response, on_delete=models.CASCADE)

    def __str__(self):
        base = str(super())
        return f'{base} - {self.response} - {self.answer_date}'

web_interface/core/templates/about_me.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About me</title>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            body, html {
              height: 100%;
              margin: 0;
              font: 400 15px/1.8 "Lato", sans-serif;
              color: #777;
            }

            .bgimg-1, .bgimg-2, .bgimg-3 {
              position: relative;
              opacity: 1;
              background-position: center;
              background-repeat: no-repeat;
              background-size: cover;

            }
            .bgimg-1 {
              background-image: url("https://images2.alphacoders.com/862/thumb-1920-862737.png");
              height: 100%;
            }

            .caption {
              position: absolute;
              left: 0;
              top: 50%;
              width: 100%;
              text-align: center;
              color: #000;
            }

            .caption span.border {
              background-color: #111;
              color: #fff;
              padding: 18px;
              font-size: 25px;
              letter-spacing: 10px;
            }

            h3 {
              letter-spacing: 5px;
              text-transform: uppercase;
              font: 20px "Lato", sans-serif;
              color: #111;
            }

        </style>
    </head>
</head>
<body>

<div class="bgimg-1">

</div>


</body>

</html>

web_interface/core/templates/change_password.html
{% extends "layouts/base.html" %}

{% block title %} Change password {% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="fade-in">
        <div class="col-md-15">
            <div class="card">
                <div class="card-header"><strong>Change your password</strong></div>
                <div class="card-body">
                    {% if form.errors %}
                    {% for field in form %}
                    {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% elif success %}
                    <div class="alert alert-success">
                        <strong>Your password has been successfully updated</strong>
                    </div>
                    {% endif %}
                    <form action="/change_password/" class="form-horizontal" enctype="multipart/form-data"
                          method="post">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label class="col-md-3 col-form-label" for="old_password">Old password</label>
                            <div class="col-md-9">
                                <input class="form-control" id="old_password" name="old_password"
                                       required
                                       type="password">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3 col-form-label" for="new_password1">New password</label>
                            <div class="col-md-9">
                                <input class="form-control" id="new_password1" name="new_password1"
                                       required
                                       type="password">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3 col-form-label" for="new_password2">New password (check)</label>
                            <div class="col-md-9">
                                <input class="form-control" id="new_password2" name="new_password2"
                                       required
                                       type="password">
                            </div>
                        </div>
                        <div class="text-center">
                            <button class="btn btn-sm btn-primary" name="login" type="submit">Submit</button>
                            <button class="btn btn-sm btn-danger" type="reset"> Reset</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% block javascripts %}
<!-- Specific Page JS goes HERE  -->
{% endblock javascripts %}

{% endblock content %}

web_interface/core/templates/dashboard.html
{% extends "layouts/base.html" %}

{% block title %} Dashboard {% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="fade-in">
        <div class="row">
            <div class="col-sm-4 col-lg-4">
                <div class="card text-white bg-success">
                    <div class="card-body">
                        <div class="text-muted text-right mb-4">
                            <svg class="c-icon c-icon-2xl">
                                <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-user-follow"></use>
                            </svg>
                        </div>
                        <div class="text-value-lg">{{number_associated_patients}}</div>
                        <small class="text-muted text-uppercase font-weight-bold">Associated patients</small>
                    </div>
                </div>
            </div>
            <!-- /.col-->
            <div class="col-sm-4 col-lg-4">
                <div class="card text-white bg-info">
                    <div class="card-body">
                        <div class="text-muted text-right mb-4">
                            <svg class="c-icon c-icon-2xl">
                                <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-task"></use>
                            </svg>
                        </div>
                        <div class="text-value-lg">{{ submitted_questions }}</div>
                        <small class="text-muted text-uppercase font-weight-bold">Submitted questions</small>
                    </div>
                </div>
            </div>
            <!-- /.col-->
            <div class="col-sm-4 col-lg-4">
                <div class="card text-white bg-warning">
                    <div class="card-body">
                        <div class="text-muted text-right mb-4">
                            <svg class="c-icon c-icon-2xl">
                                <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-speech"></use>
                            </svg>
                        </div>
                        <div class="text-value-lg">{{ total_answers }}</div>
                        <small class="text-muted text-uppercase font-weight-bold">Total answers</small>
                    </div>
                </div>
            </div>
            <!-- /.col-->
        </div>

        <!-- /.row-->
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Response statistics</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <div>
                                    <h5 style="text-align: center">Answers per hour (%)</h5>
                                </div>
                                <hr class="mt-0">
                                {% for key, value in answers_per_hour.items %}
                                <div class="progress-group mb-4">
                                    <div class="progress-group-prepend"><span
                                            class="progress-group-text">{{key}}</span>
                                    </div>
                                    <div class="progress-group-bars">
                                        <div class="progress progress-xl">
                                            <div aria-valuemax="100" aria-valuemin="0"
                                                 class="progress-bar progress-bar-striped progress-bar-animated bg-warning"
                                                 role="progressbar"
                                                 style="width: {{value}}%"></div>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                            <!-- /.col-->
                            <div class="col-sm-6">
                                <div class="row">
                                </div>
                                <!-- /.row-->
                                <div>
                                    <h5 style="text-align: center">Patients per gender (%)</h5>
                                </div>
                                <hr class="mt-0">
                                <div class="progress-group mb-5">
                                    <div class="progress-group-header">
                                        <svg class="c-icon progress-group-icon">
                                            <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-user"></use>
                                        </svg>
                                        <div>Male</div>
                                        <div class="mfs-auto font-weight-bold">{{ male_percentage }} %</div>
                                    </div>
                                    <div class="progress-group-bars">
                                        <div class="progress progress">
                                            <div aria-valuemax="100" aria-valuemin="0"
                                                 class="progress-bar progress-bar-striped progress-bar-animated bg-success"
                                                 role="progressbar"
                                                 style="width: {{ male_percentage }}%"></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="progress-group mb-5">
                                    <div class="progress-group-header">
                                        <svg class="c-icon progress-group-icon">
                                            <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-user-female"></use>
                                        </svg>
                                        <div>Female</div>
                                        <div class="mfs-auto font-weight-bold">{{ female_percentage }}%</div>
                                    </div>
                                    <div class="progress-group-bars">
                                        <div class="progress progress">
                                            <div aria-valuemax="100" aria-valuemin="0"
                                                 aria-valuenow="{{ female_percentage }}"
                                                 class="progress-bar progress-bar-striped progress-bar-animated bg-info"
                                                 role="progressbar"
                                                 style="width: {{ female_percentage }}%"></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="progress-group mb-5">
                                    <div class="progress-group-header">
                                        <svg class="c-icon progress-group-icon">
                                            <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-people"></use>
                                        </svg>
                                        <div>Other</div>
                                        <div class="mfs-auto font-weight-bold">{{ other_percentage }} %</div>
                                    </div>
                                    <div class="progress-group-bars">
                                        <div class="progress progress">
                                            <div aria-valuemax="100" aria-valuemin="0"
                                                 aria-valuenow="{{ other_percentage }}"
                                                 class="progress-bar progress-bar-striped progress-bar-animated bg-danger"
                                                 role="progressbar"
                                                 style="width: {{ other_percentage }}%"></div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <!-- /.col-->
                        </div>
                        <!-- /.row-->
                        <br>
                        {% if top_patients %}
                        <div>
                            <h3 style="text-align: center">Top 5</h3>
                            <br>
                        </div>
                        <table class="table table-responsive-sm table-hover table-outline mb-0">
                            <thead class="thead-light">
                            <tr>
                                <th class="text-center">
                                    <svg class="c-icon">
                                        <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-face"></use>
                                    </svg>
                                </th>
                                <th style="text-align: center; vertical-align: middle;">Username</th>
                                <th style="text-align: center; vertical-align: middle;">Language</th>
                                <th style="text-align: center; vertical-align: middle;">Gender</th>
                                <th style="text-align: center; vertical-align: middle;">Total responses</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for patient in top_patients %}
                            <tr>
                                <td style="text-align: center; vertical-align: middle;">
                                    <img height="60" src="data:image/png;base64,{{ patient.0.picture}}"
                                         style="border-radius: 50%;"
                                         width="50">
                                </td>
                                <td style="text-align: center; vertical-align: middle;">
                                    {{ patient.0.username }}
                                </td>
                                <td style="text-align: center; vertical-align: middle;">
                                    {% if patient.0.language == "ES" %}
                                    <svg class="c-icon c-icon-xl">
                                        <use xlink:href="/static/assets/vendors/@coreui/icons/svg/flag.svg#cif-es"></use>
                                    </svg>
                                    {% else %}
                                    <svg class="c-icon c-icon-xl">
                                        <use xlink:href="/static/assets/vendors/@coreui/icons/svg/flag.svg#cif-gb"></use>
                                    </svg>
                                    {% endif %}
                                </td>
                                <td style="text-align: center; vertical-align: middle;">
                                    {{ patient.0.get__gender_display }}
                                </td>
                                <td style="text-align: center; vertical-align: middle;">
                                    {{ patient.1 }}
                                </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        {% endif %}
                    </div>
                </div>
            </div>
            <!-- /.col-->
        </div>
        <!-- /.row-->
    </div>
</div>

{% endblock content %}

{% block javascripts %}

<script src="/static/assets/vendors/@coreui/coreui-chartjs/js/coreui-chartjs.bundle.js"></script>
<script src="/static/assets/js/main.js"></script>

{% endblock javascripts %}

web_interface/core/templates/delete_account.html
{% extends "layouts/base.html" %}

{% block title %} Delete account {% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="fade-in">
        <div class="col-md-8" style="margin: 0 auto;float: none;margin-bottom: 10px;">
            <div class="card">
                <div class="card-header">
                    <strong>Are you sure you want to delete your account ?</strong>
                    <br>
                    Your created questions will also be deleted.
                </div>
                <div class="card-body">
                    <form action="{{request.path}}" class="form-horizontal"
                          enctype="multipart/form-data"
                          method="post">
                        {% csrf_token %}
                        <div class="text-center">
                            <button class="btn btn-sm btn-danger" name="login" type="submit">Confirm</button>
                            <a href="">
                                <button class="btn btn-sm btn-primary" type="button"> Back</button>
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% block javascripts %}
<!-- Specific Page JS goes HERE  -->
{% endblock javascripts %}

{% endblock content %}

web_interface/core/templates/page-blank.html
{% extends "layouts/base.html" %}

{% block title %} PAGE_TITLE {% endblock %} 

{% block content %}

    PAGE_CONTENT

{% endblock content %}

{% block javascripts %}
<!-- Specific Page JS goes HERE  -->
{% endblock javascripts %}